#!/bin/bash

# Try to find waffles.conf in either /etc/waffles or ~/.waffles
if [[ -f "/etc/waffles/waffles.conf" ]]; then
  source /etc/waffles/waffles.conf
fi

if [[ -f ~/.waffles/waffles.conf ]]; then
  source ~/.waffles/waffles.conf
fi

upstreamconf__=$(dirname $(readlink -e $BASH_SOURCE) )/waffles.conf
if [[ -f $upstreamconf__ ]]; then
  source $upstreamconf__
fi
unset upstreamconf__

# If CONFIG_FILE or WAFFLES_CONFIG_FILE is set, prefer it
if [[ -n $CONFIG_FILE ]]; then
  source "$CONFIG_FILE"
fi

if [[ -n $WAFFLES_CONFIG_FILE ]]; then
  source "$WAFFLES_CONFIG_fILE"
fi

# Make sure WAFFLES_DIR has a value
if [[ -z $WAFFLES_DIR ]]; then
  echo "WAFFLES_DIR is not set."
  exit 1
fi

# Read in the Waffles functions and resources
source "$WAFFLES_DIR/lib/init.sh"

# Apply the wafflescript
source "${1:-/dev/stdin}"
